### ISSUE TITLE
Can't set value outside of ViewDidLoad

### ISSUE THREAD

**Issue by Ashernor** [EngrAhsanAli/AARatingBar#1]
Hi,

I'm having a strange bug, I use your very nice module in a Objective-C project. I want to setup the value of ratings after a small API call and I noticed I can't change the value outside of ViewDidLoad.

I did some tests and even trying to set the value in viewDidAppear is not working.

Kind regards

**Comment by EngrAhsanAli** [comment]
Hi Ashernor,

Please share your code snippet that how you are trying to set the ratingBar `value` in `viewDidLoad`.
For me, its simply working perfect by setting value as `ratingBar.value = 3` in swift.

Regards,

**Comment by uditha2233** [comment]
Hi
I also have the same issue. I am getting rating data from an API. But I can't update the rating star value after the api call. But if I hardcode the `ratingBar.value = 3` inside  `viewDidLoad`  it works fine. Did you found any solution for this issue?

**Comment by osvaldobringas** [comment]
I know that is too late but to solve this issue this work for me:

```
 DispatchQueue.main.async {
                self.ratingbarView.value = 4.0 // value from api response
                self.ratingbarView.setNeedsDisplay()
            }
```

write the code above after the api response
