### ISSUE TITLE
Carthage error

### ISSUE THREAD

**Issue by oddysee** [EngrAhsanAli/AARatingBar#2]
Building using Carthage results in this error - `Dependency "AARatingBar" has no shared framework schemes`. Perhaps you need to check-in this file? `.xcodeproj/xcshareddata/xcschemes`

**Comment by EngrAhsanAli** [comment]
Please refer your carthage dependeny to the master branch like this:
github "EngrAhsanAli/AARatingBar" "master"

Hope it will work like a charm! 
Thank you for your interest.
