### ISSUE TITLE
iPhone 6S 11.1 iOs issue

### ISSUE THREAD

**Issue by lutc** [EngrAhsanAli/AARatingBar#5]
The filled stars are smaller then unfilled.
![screen shot 2017-11-09 at 18 02 38](https://user-images.githubusercontent.com/1345360/32612040-3f3bb0d0-c578-11e7-81a0-36c91ee949b8.png)

**Comment by leotalha** [comment]
Same issue here

**Comment by leotalha** [comment]
I have read the code and did a small change in AARatingBar.swift file.

to fix, please replace the function getRatingView with this one


`func getRatingView(withIcon text: String) -> UIView {
        let view = UIView(frame: self.bounds)
        view.clipsToBounds = true
        view.backgroundColor = .clear
        
        var ratingWidth2 = ratingWidth
        if text == filledIcon {
            ratingWidth2 += 0
        }
        
        
        var frame = self.bounds
        frame.size.width = ratingWidth2
        
        let fitSize = CGSize(width: ratingWidth2, height: bounds.height)
        
        for position in 0 ..< maxValue {
            
            frame.origin.x = CGFloat(position) * ratingWidth2
            
            let starView = UILabel(frame: frame)
            starView.text = text
            starView.textColor = color
            
            var increaseRate : CGFloat!
            let screenWidth = UIScreen.main.bounds.width
            
            if screenWidth == 375 ||  screenWidth == 414 {
                increaseRate = 5
            }
            else if screenWidth > 414 {
                increaseRate = 10
            }else if screenWidth < 370 {
                increaseRate = 4
            }
            if text == filledIcon {
                starView.font = starView.font.withSize(ratingWidth2+increaseRate)
            }
            else{
                starView.font = starView.font.withSize(ratingWidth2)
            }
            starView.sizeThatFits(fitSize)
            view.addSubview(starView)
        }
        return view
    }`

**Comment by EngrAhsanAli** [comment]
Hi,

I have updated the library with this bug fix, please check the latest version of https://cocoapods.org/pods/AARatingBar
