### ISSUE TITLE
Not run with IOS 13

### ISSUE THREAD

**Issue by Tetsuo41** [EngrAhsanAli/AARatingBar#7]
Hi.

It is a good library. It worked well for iOS 11 and 12. But with 13, it stopped working. Please help.

Regards.
![44581](https://user-images.githubusercontent.com/18426410/65343370-1d716b00-dbd5-11e9-93a1-0b92a7b217a9.jpg)
![Sin título](https://user-images.githubusercontent.com/18426410/65343673-d2a42300-dbd5-11e9-91c1-dfd58d79eecb.png)

**Comment by jahnaviredspark** [comment]
I have same issue

**Comment by dennygajera** [comment]
Hi, I had the same issue. 
this is not a permanent solution. but you can try this one,

1) open AARatingBar
2) In getRatingView() ,
**replace** 
frame.size.width = ratingWidth
**with**
frame.size.width = 50

Clean Build folder and Run.

**Comment by Tetsuo41** [comment]
Thanks. I will try it.

**Comment by EngrAhsanAli** [comment]
Hi

Thanks for sharing the feedback and apologies for delaying the response from my side.

I have updated the library with iOS13 bug fix and included custom font icon support, please use the latest version of library https://cocoapods.org/pods/AARatingBar
