### ISSUE TITLE
Icon is cutting

### ISSUE THREAD

**Issue by paulocoutinhox** [EngrAhsanAli/AARatingBar#8]
Icon is cutting

![IMG_461D155013D3-1](https://user-images.githubusercontent.com/395096/85787807-56a9af00-b702-11ea-9c7a-379dd2c73677.jpeg)

```swift
ratingView = AARatingBar()
ratingView.translatesAutoresizingMaskIntoConstraints = false
ratingView.maxValue = 5
ratingView.color = UIColor(hexString: "#FFE500")!
contentContainer.addSubview(ratingView)

ratingView.snp.makeConstraints {
    $0.centerX.equalToSuperview()
    $0.top.equalToSuperview().offset(20)
    $0.height.equalTo(40)
    $0.width.equalToSuperview()
    $0.margins.equalTo(50)
}
```

**Comment by EngrAhsanAli** [comment]
The size of stars is having dynamic heights from the superview.
Pull the version 1.1 and make the adjustment from the property **spaceOffset**  like below:

`ratingbar.spaceOffset = 1.2`
